name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: false
        default: 'Manual Release'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ARENA_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Project Version from Git Tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF_NAME}"

      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon --stacktrace

      - name: Publish to UTF Maven Repository
        run: ./gradlew publishAllPublicationsToUtfMvnRepository --no-daemon --stacktrace
        env:
          UTF_MVN_USER: ${{ secrets.UTF_MVN_USER }}
          UTF_MVN_PASS: ${{ secrets.UTF_MVN_PASS }}

      - name: List all JAR files
        run: find . -name "*.jar" -type f -not -path "*/build/tmp/*" -not -path "*/run/*"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            plugin/build/libs/*.jar

      - name: Set Release Name
        id: set_release_name
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "release_name=${{ github.event.inputs.release_name }} (v${{ steps.get_version.outputs.version }})" >> $GITHUB_OUTPUT
          else
            echo "release_name=Release ${{ github.ref_name }} (v${{ steps.get_version.outputs.version }})" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.set_release_name.outputs.release_name }}
          draft: false
          prerelease: false
          files: |
            plugin/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
